---
title: "Website Generator"
output: html_document
---

```{r setup1, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)

library(dplyr)
library(knitr)
library(kableExtra)
library(readxl)
library(glue)

data_file <- "mikes-data.xlsx"

#rmarkdown::render("ttt.Rmd", output_file = "docs/mike_johnson_cv.pdf")
```


```{r create-table}
create_table <- function(table = NULL, file_name = NULL, removeHeaders = TRUE, caption = NULL) {
  
  table <- rbind(rep("", ncol(table)), table) %>%
    kable(escape = FALSE, caption = caption, align = c("l")) %>%
    kable_styling(bootstrap_options = c("hover"))
  
  if (removeHeaders) {
    table <- gsub("<thead>.*</thead>", "", table)
  }
  fileConn <- file(paste0('docs/', file_name))
  writeLines(table, fileConn)
  close(fileConn)
}
```

```{r update-scss}
sass::sass(
  sass::sass_file("docs/resources/scss/miketheme.scss"),
  output = "docs/resources/css/bootstrap.css",
  options = sass::sass_options(output_style = "nested")
)
```

## Publications

```{r}
library(scholar)

cites = get_publications('MrXM9cgAAAAJ') %>% 
   filter(!grepl("AGU|EGU|Meeting|meeting|Preprint|SUMMER INSTITUTE|University|Https|Universities|Frontiers in Hydrology", journal)) %>% 
  filter(journal != "")

for(i in 1:nrow(cites)){
  if(!grepl("JM Johnson|J Johnson|M Johnson", cites$author[i])){
    cites$author[i] = get_complete_authors(id = 'MrXM9cgAAAAJ', pubid = cites$pubid[i])
  }
}

cites %>% 
  mutate(
    url = glue::glue('https://scholar.google.com/citations?view_op=view_citation&hl=en&user=MrXM9cgAAAAJ&citation_for_view=MrXM9cgAAAAJ:{pubid}'),
    citation = paste0(gsub("JM Johnson", '<b>J.M Johnson</b>', author), 
                      ' (', year, "). ",
                      text_spec(title, italic = TRUE, link = url), ". ",
                      text_spec(journal, italic = FALSE), '.')
  ) %>%
    arrange(-year, - cites) %>% 
    #mutate(citation = paste(paste0("[", n():1, "]     "), citation)) %>% 
    select(Year = year, `Peer Review Publications` = citation) %>% 
    group_by(Year) %>% 
    mutate(Year = c(Year[1], rep("", n() - 1))) %>% 
    ungroup() %>% 
    mutate(` ` = n():1) %>% 
  select(Year, ` `, `Peer Review Publications`) %>% 
    create_table(file_name = "peer_publications.html", removeHeaders = FALSE)

```

## Teaching 

```{r}
teaching = read_excel(data_file, sheet = "teaching")

teaching <- teaching %>%
  mutate(quarter = factor(quarter, levels = c("Fall", "Winter", "Spring", "Summer"), 
                          ordered = T),
         class_link = ifelse(is.na(link), class, 
                             paste0('<a href="',link, '">', class, '</a>'))) %>% 
  group_by(type, class, class_link, quarter, professor, division) %>%
  mutate(points = as.numeric(year) + as.numeric(quarter)/10) %>% 
  summarise(year = paste(year,collapse=', '), 
            points = max(points)) %>% 
  tidyr::unite(data, quarter, year, sep = " ") %>% 
  arrange(desc(points)) 
  

teaching_html <- teaching %>%
  filter(type == "Instructor") %>% 
  mutate(
    ' ' = paste0(text_spec(class_link, bold = TRUE, escape = FALSE), "<br>", 
                 division, " - ", text_spec(professor, italic = TRUE))) %>%
  ungroup() %>% 
  select(data, ' ') %>%
  rename('Instructor' = data)

teaching_assisstant_html <- teaching %>%
   filter(type == "Teaching Assisstant") %>% 
   mutate(
    ' ' = paste0(text_spec(class_link, bold = TRUE, escape = FALSE), "<br>", 
                 division, " - ", text_spec(professor, italic = TRUE))) %>%
  ungroup() %>% 
  select(data, ' ') %>%
  rename('Teaching Assistant' = data)

create_table(table = teaching_html, file_name = 'teaching.html', removeHeaders = FALSE)
create_table(table = teaching_assisstant_html, file_name = 'teaching-assisstant.html', removeHeaders = FALSE)

```

## Affiliations

```{r}
# Affiliations Table

affiliations = readxl::read_xlsx(data_file, sheet = "coauthors")

# Affiliations Map
require(leaflet)
require(htmltools)
library(dplyr)

authors  = lapply(paste("<strong>", affiliations$Name, "</strong><br>", gsub(";", "<br>", affiliations$people)),  htmltools::HTML)

# Generate Map
affiliation_map = leaflet(affiliations, options = leafletOptions(zoomControl = FALSE, 
                                                                 minZoom = 2, maxZoom = 2, dragging = FALSE)) %>%
  addProviderTiles(providers$CartoDB.PositronNoLabels) %>%
  addCircleMarkers(lng = ~as.numeric(Long), lat = ~as.numeric(Lat),
                   radius = ~lengths(strsplit(affiliations$people, ";"))*4,
                   color = ~ifelse(affiliations$Name == "UCSB Geography", "red", "navy"),
                   stroke = FALSE,
                   fillOpacity = 0.7, 
                   label = authors,
                   labelOptions =  labelOptions(keepInView = TRUE, autoPan = FALSE,
                                         style = list(
                                           "box-shadow" = "9px 9px rgba(0,0,0,0.25)",
                                           "border-color" = "navy",
                                           "padding-right" = "10px",
                                           "background-color" = "white")))

# Create HTML file

f<-paste0(getwd(), "/docs/affiliations_map.html")
htmlwidgets::saveWidget(affiliation_map,file.path(normalizePath(dirname(f)),basename(f)))
```


## Footer

```{r}
# Generate Footer

footer = paste0('<div class=" container">
            <div class="row">
              <div class="col-md-6">
              <p>
                🏔️🌲🌄 Fort Collins, Colorado 🌄🌲🏔 <br />
              </p>
            </div>
            <div class="col-md-6 text-right">
              <a href="https://github.com/mikejohnson51" target="_blank" class="social-link"><i class="fab fa-github fa-2x grow"></i></a>
              <a href="https://scholar.google.com/citations?hl=en&user=MrXM9cgAAAAJ&view_op=list_works&sortby=pubdate" target="_blank" class="social-link fa-2x"><i class="ai ai-google-scholar grow"></i></i></a>
              <a href="https://www.researchgate.net/profile/Mike_Johnson29" target="_blank" class="social-link fa-2x"><i class="ai ai-researchgate grow"></i></a>
              <a href="mailto:mike.johnson@geog.ucsb.edu" target="_blank" class="social-link fa-2x"><i class="far fa-envelope grow"></i></i></a>
              <p>Last Updated: ', format(Sys.time(), "%B %e, %Y"), '</p>
            </div>
          </div>
        </div>')

fileConn<-file('docs/footer.html')
writeLines(footer, fileConn)
close(fileConn)
```

