---
output: 
 pdf_document:
  includes: 
   in_header: ../style_1_inchmargin.tex
fontsize: 12pt
subparagraph: yes
---

```{r setup, include=FALSE}
source("../global.R")
form = "Teaching Statement"
```

\let\oldrule=\rule
\renewcommand{\rule}[1]{\vspace{-25pt}\oldrule{\linewidth}}

\lfoot{\textcolor{gray}{J.M. Johnson}}
\cfoot{\textcolor{gray}{`r form`}}
\rfoot{\textcolor{black}{\thepage}}
\renewcommand{\footrulewidth}{0.4pt}
\futurelet\TMPfootrule\def\footrule{\color{gray}{\TMPfootrule}}

\vspace{3mm}
\centerline{\textbf{\textsl{J. Michael Johnson $\cdot$ `r form`}}}
\centerline{\textcolor{gray}{University of California, Santa Barbara, California $\cdot$ Department of Geography}}
\vspace{-3mm}
\hspace{-3mm}{\uline{\textsc{\textcolor{black}{}}\hfill}\newline}

The University of California, Santa Barbara offers one of the top geography departments in the world, and I have been fortunate to learn from a number of motivating instructors as a teaching assistant (TA) for lower division, upper division, and graduate level courses on topics including water quality, software engineering, cartography and data visualization, remote sensing, and physical geography. In both 2019 and 2020 I was nominated for the department _Excellence in Teaching_ award by our faculty, and for the University _Teaching Assistant_ award by my students. One of my proudest accomplishments was being allowed to independently design and teach our department’s Introduction to GIS course (available \href{https://mikejohnson51.github.io/spds/}{here}). I redesigned this course as an Introduction to Geoinformatics to fill a departmental gap in data science and geospatial programming. In summer of 2020, due to the COVID-19 campus closure,  I taught this class remotely to 48 students from around the world, most of whom had never programed. In response to student demand, and a recognition that programming skills are now required of Geoscience professionals, I was offered the opportunity to refine this class as a permanent department offering and a pre-requisite for undergraduates and the newly established Masters in GIS. I will be hired as a lecturer at UCSB to teach this again in the 2021 summer session.

At UCSB, I have had a range of experience teaching in traditional, hybrid, remote and online classrooms. In addition to my summer course, I have been a remote TA for three classes:  Modeling and Programming for the Geo-Sciences, Introduction to Remote Sensing, and Advanced Remote Sensing. Each summer, I have TA’d and administered a synchronous online, writing-based course on climate change  for non-majors. Further, my advisor created a hybrid course in which labs are given in person, but lectures are activity based and asynchronous. I have both TA’d  and helped develop labs for this course which is now offered across the University of California system. Each of these experiences have helped me better understand the complexity of teaching through different platforms and has prepared me to teach in an increasingly remote and/or hybrid world.

With respect to teaching interests at Mines, I enjoy helping students use programming and computational methods to solve problems, document and share their work, and guide the way they think, research and advance their learning. I would be interested in providing  data science, data management, and data visualization courses that could serve as a common beginning for students across the Computational Science and Data Analytics allied departments. In line with the GIS and Geoinformatics Interdisciplinary group and the Geology and Geological Engineering Department, I would enjoy teaching a range of geospatial data science and geostatistics courses including GIS Applications, spatial modeling and data models, remote sensing and analysis, and applied machine learning for environmental research. In the Hydrologic Science and Engineering program and aligned with the department of Civil & Environmental Engineering, I would be prepared to teach a range of courses covering topics such as hydrologic analysis and design, surface water hydrology, rainfall-runoff modeling, and watershed modeling. Equally, I would be eager to organize graduate seminars that take a deep dive into methods and technologies including data science, geospatial analysis, linked data and semantic technologies, or hydrologic and land surface modeling (e.g., NOAH-MP, WRF-Hydro).

From my experiences as a student, a TA, and an instructor, a few aspects guide how I prefer to structure a class regardless of platform. My teaching philosophy is certainly a product of my undergraduate university’s philosophy of  “Learn by Doing,”  and I am a strong believer that classes should: (1)  be challenge based and flexible, (2) teach a practical skill alongside a strong theoretical foundation, and (3) require students to integrate the skill and theory to produce something meaningful. 

I use programming as a way to teach and reinforce concepts. While it’s rare to spend time “learning to program,” code is used throughout lectures and is required to solve daily exercises and labs. One of the biggest stressors and areas of inequity in the classroom expressed by past students are timed, memorization heavy tests that favor populations who have been trained to perform under those circumstances. Instead, my courses evaluate students with low stress, but high expectation, projects that push their ability to find and synthesize information, clean and work with real-world data, and actively problem solve and communicate results. 

Core learning objectives are clearly established at the beginning of the course; however, the timeline and the way material is presented remains flexible to meet student needs. Equally, students are encouraged to see the classroom as a collaborative rather than competitive environment in which the instructor is an active participant. All courses start with a steep learning curve that motivates students to collaborate, overcome their initial fears of coding, and open channels of communication with me about what is and is not working. 

Lecture material aims to be deep and comprehensive, so students are exposed to the central concepts, theories, and organizations in a field, while building the foundations to independently find material. They are not expected to retain every detail from lecture, but rather how to recall, reference, and find material as they need it. To support this process, every lecture is followed by a completion-based assignment that requires the lecture concepts to be translated to code in a way that represents a process or idea. The labs each week challenge students to mix and extend these daily exercises and apply them to a real-world topical problems that they document and share using reproducible version-controlled technology. These assignments help students work at their own pace, grapple with the material, seek help, and better relate concepts to real-world applications.

In a world that is increasingly competitive, visual, and online, students need ways to showcase their skills to employers and graduate admission committees. Thus, each class aims to develop something tangible that students can take with them. These projects are introduced at the beginning of the course and mature through the quarter by scaling lab and lecture assignments. In my Geoinformatics course this was a personal website that highlighted their labs, resume, and an ‘About Me’ page. In the first week’s lab students built this website to reinforce reproducible data science practices and each week they added to it linking their labs and material from previous classes. The course final was to fine tune this website, while adjusting the About Me page to verbalize what they had learned, and document their abilities as a spatial data scientist. Already, four students have commented on these webpages being key to securing post graduate jobs or internships. 

In the end, I truly enjoy teaching. One of the most appealing features of a career in academics is the ability to do both cutting edge research and teach students material I am enthusiastic about.  I am particularly excited about the opportunity to teach as a university like Mines that embraces a learn by doing philosophy, devotes significant time and resources to educating students, has an established tradition of faculty and students working together, and strong interdisciplinary programs focused on Geoinformatics and water resources research.
